---
apiVersion: v1
kind: Service
metadata:
    name: task-backend-service
    namespace: apps
spec:
    selector:
        app: task-backend
    ports:
        -   protocol: TCP
            port: 8000
            targetPort: 8000
    type: ClusterIP
