# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v6.0.0
        hooks:
            -   id: check-illegal-windows-names
            -   id: check-merge-conflict
            -   id: check-yaml
            -   id: end-of-file-fixer
            -   id: mixed-line-ending
                args:
                    - --fix=lf
            -   id: trailing-whitespace

    -   repo: https://github.com/psf/black
        rev: 25.9.0
        hooks:
            -   id: black

    -   repo: https://github.com/pycqa/isort
        rev: 6.0.1
        hooks:
            -   id: isort
                name: isort (python)

    -   repo: https://github.com/astral-sh/ruff-pre-commit
        rev: v0.13.1
        hooks:
            -   id: ruff-check
