@task_id = 08693f18-483d-4076-a145-4a6516c89a61

### Analyze Task
POST {{BASE_URL}}/tasks/{{task_id}}/analyze
Authorization: Bearer {{$auth.token("password-auth")}}

### Assist Task
POST {{BASE_URL}}/tasks/{{task_id}}/assist
Authorization: Bearer {{$auth.token("password-auth")}}
