@task_id = 09c89b0d-5102-4728-bae2-5897612deca9
@other_email = hassan@hassanamr.com

### List All Tasks
GET {{BASE_URL}}/tasks/
Authorization: Bearer {{$auth.token("password-auth")}}


### Create Task
POST {{BASE_URL}}/tasks/
Authorization: Bearer {{$auth.token("password-auth")}}
Content-Type: application/json

{
    "title": "Task One",
    "description": "This is the first task we need to complete.",
    "priority": "Medium",
    "status": "Pending",
    "deadline": "2025-10-21T16:09:58.165274"
}

### Get Task
GET {{BASE_URL}}/tasks/{{task_id}}
Authorization: Bearer {{$auth.token("password-auth")}}

### Edit Task
PUT {{BASE_URL}}/tasks/{{task_id}}
Authorization: Bearer {{$auth.token("password-auth")}}
Content-Type: application/json

{
    "description": "Updated description."
}

### Delete Task
DELETE {{BASE_URL}}/tasks/{{task_id}}
Authorization: Bearer {{$auth.token("password-auth")}}

### Add Subscription
POST {{BASE_URL}}/tasks/subscribe/{{task_id}}/{{other_email}}
Authorization: Bearer {{$auth.token("password-auth")}}

### Remove Subscription
DELETE {{BASE_URL}}/tasks/subscribe/{{task_id}}/{{other_email}}
Authorization: Bearer {{$auth.token("password-auth")}}
