---
apiVersion: v1
kind: Service
metadata:
    name: postgres
    namespace: postgres
    labels:
        app: postgres
spec:
    selector:
        app: postgres
    ports:
        -   protocol: TCP
            name: postgres
            port: 5432
            targetPort: 5432
    type: ClusterIP
