---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: task-frontend
    namespace: apps
    labels:
        app: task-frontend
spec:
    replicas: 2
    selector:
        matchLabels:
            app: task-frontend
    template:
        metadata:
            labels:
                app: task-frontend
        spec:
            containers:
                -   name: task-frontend
                    image: hassanabouelela/task-ai-frontend:latest
                    ports:
                        -   containerPort: 3000
                    resources:
                        limits:
                            cpu: "500m"
                            memory: "512Mi"
                        requests:
                            cpu: "200m"
                            memory: "256Mi"
