---
apiVersion: v1
kind: Service
metadata:
    name: task-frontend-service
    namespace: apps
spec:
    selector:
        app: task-frontend
    ports:
        -   protocol: TCP
            port: 3000
            targetPort: 3000
    type: ClusterIP
