name: Backend CI

on:
    push:
        paths:
            - "backend/**"
            - ".github/workflows/backend.yml"
    pull_request:
        paths:
            - "backend/**"

jobs:
    lint-test:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: backend
                shell: bash

        steps:
            -   uses: actions/checkout@v4

            -   name: Install Python Dependencies
                uses: HassanAbouelela/actions/setup-python@setup-python_v1.6.0
                with:
                    install_args: "--with dev"
                    python_version: "3.13"
                    working_dir: "backend"

            -   name: Black (check)
                run: poetry run black --check .

            -   name: Isort
                run: poetry run isort --check-only .

            -   name: Ruff
                run: poetry run ruff check .

            # TODO: Add database if required for tests
            -   name: Pytest
                run: poetry run pytest
                env:
                    CI: true
                    DATABASE_URL: postgresql+psycopg://postgres:postgres@localhost:5432/postgres
